### ISSUE TITLE
[google-maps] Getting Fatal error while using "Map View" on iOS

### ISSUE THREAD

**Issue by mukul-kmr-jha** [ionic-team/capacitor-plugins#1392]
## Bug Report

Google maps is not loading and instead getting the following error on iOS device, on the web its working fine.

```
CapacitorGoogleMaps/Map.swift:121: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2023-01-27 17:10:56.144713+0530 App[9806:2924737] CapacitorGoogleMaps/Map.swift:121: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
(lldb) 
```

### Capacitor Version
```

Ionic:

   Ionic CLI                     : 5.4.16 (/Users/mukul/.nvm/versions/node/v14.20.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.9.4
   @angular-devkit/build-angular : 0.1102.19
   @angular-devkit/schematics    : 11.2.19
   @angular/cli                  : 11.2.19
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 4.4.0
   @capacitor/core : 4.4.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (2 plugins total)

Utility:

   cordova-res (update available: 0.15.4) : 0.14.1

```

```
PASTE OUTPUT HERE
```

### Platform(s)
Issue is on iOS

### Current Behavior
Template changes

container.component.html
```html
   <ion-header>HEADER DESIGN</ion-header>
   <ion-content>
        <app-map-view class="map-container"></app-map-view>
        <other-ui></other-ui> --> some other UI item to be shown on top of the map
  </ion-content>
```

map-view.component.html
```html
<capacitor-google-map #mapRef></capacitor-google-map>
```

CSS changes
```css

.map-container {
    display: block;
    position: absolute;
    top: 0; 
    left: 0;
    width: 100vw;
    height: 100vh;
}

capacitor-google-map {
    display: block;
    width: 100%;
    height: 100%;
}

```

### Expected Behavior
Map should be rendered.
